#!/bin/sh

# set appliance for a node

if [ $# -ne 2 ]
  then
    echo "======================="
    echo "Set appliance for a node."
    echo "Usage: $0 <srv> <appliance>"
    echo "======================="
exit 1
fi
TRGT=$1
APPLIANCE=$2

stack set host box $TRGT appliance=$APPLIANCE

# display current host/appliance
stack list host $TRGT
