#!/bin/sh

if [ $# -eq 0 ]
  then
    echo "======================="
    echo "Remove box."
    echo "Usage: $0 <box>"
    echo "======================="
exit 1
fi

stack remove box $1
stack list box $1
