#!/bin/sh

# add cart to a box

if [ $# -ne 2 ]
  then
    echo "======================="
    echo "Add cart to a box."
    echo "Usage: $0 <cart> <box>"
    echo "======================="
exit 1
fi
CART=$1
BOX=$2

stack enable cart $CART box=$BOX

# display current host/box
stack list box $BOX
