#!/bin/sh

# add pallet to a box

if [ $# -ne 2 ]
  then
    echo "======================="
    echo "Add pallet to a box."
    echo "Usage: $0 <cart> <box>"
    echo "======================="
exit 1
fi
PALLET=$1
BOX=$2

stack enable pallet $PALLET box=$BOX

# display pallet(s)
stack list pallet $BOX
